package common

// ICATColumnNumber is an ICAT Column number type
type ICATColumnNumber int

// column numbers
const (
	// User
	ICAT_COLUMN_USER_ID          ICATColumnNumber = 201
	ICAT_COLUMN_USER_NAME        ICATColumnNumber = 202
	ICAT_COLUMN_USER_TYPE        ICATColumnNumber = 203
	ICAT_COLUMN_USER_ZONE        ICATColumnNumber = 204
	ICAT_COLUMN_USER_INFO        ICATColumnNumber = 206
	ICAT_COLUMN_USER_COMMENT     ICATColumnNumber = 207
	ICAT_COLUMN_USER_CREATE_TIME ICATColumnNumber = 208
	ICAT_COLUMN_USER_MODIFY_TIME ICATColumnNumber = 209

	// Data Object
	ICAT_COLUMN_D_DATA_ID       ICATColumnNumber = 401
	ICAT_COLUMN_D_COLL_ID       ICATColumnNumber = 402
	ICAT_COLUMN_DATA_NAME       ICATColumnNumber = 403 // basename
	ICAT_COLUMN_DATA_REPL_NUM   ICATColumnNumber = 404
	ICAT_COLUMN_DATA_VERSION    ICATColumnNumber = 405
	ICAT_COLUMN_DATA_TYPE_NAME  ICATColumnNumber = 406
	ICAT_COLUMN_DATA_SIZE       ICATColumnNumber = 407
	ICAT_COLUMN_D_RESC_NAME     ICATColumnNumber = 409
	ICAT_COLUMN_D_DATA_PATH     ICATColumnNumber = 410 // physical path on resource
	ICAT_COLUMN_D_OWNER_NAME    ICATColumnNumber = 411
	ICAT_COLUMN_D_OWNER_ZONE    ICATColumnNumber = 412
	ICAT_COLUMN_D_REPL_STATUS   ICATColumnNumber = 413
	ICAT_COLUMN_D_DATA_STATUS   ICATColumnNumber = 414
	ICAT_COLUMN_D_DATA_CHECKSUM ICATColumnNumber = 415
	ICAT_COLUMN_D_EXPIRY        ICATColumnNumber = 416
	ICAT_COLUMN_D_MAP_ID        ICATColumnNumber = 417
	ICAT_COLUMN_D_COMMENTS      ICATColumnNumber = 418
	ICAT_COLUMN_D_CREATE_TIME   ICATColumnNumber = 419
	ICAT_COLUMN_D_MODIFY_TIME   ICATColumnNumber = 420
	ICAT_COLUMN_D_RESC_HIER     ICATColumnNumber = 422
	ICAT_COLUMN_D_RESC_ID       ICATColumnNumber = 423

	// Collection
	ICAT_COLUMN_COLL_ID          ICATColumnNumber = 500
	ICAT_COLUMN_COLL_NAME        ICATColumnNumber = 501
	ICAT_COLUMN_COLL_PARENT_NAME ICATColumnNumber = 502
	ICAT_COLUMN_COLL_OWNER_NAME  ICATColumnNumber = 503
	ICAT_COLUMN_COLL_OWNER_ZONE  ICATColumnNumber = 504
	ICAT_COLUMN_COLL_MAP_ID      ICATColumnNumber = 505
	ICAT_COLUMN_COLL_INHERITANCE ICATColumnNumber = 506
	ICAT_COLUMN_COLL_COMMENTS    ICATColumnNumber = 507
	ICAT_COLUMN_COLL_CREATE_TIME ICATColumnNumber = 508
	ICAT_COLUMN_COLL_MODIFY_TIME ICATColumnNumber = 509

	// Data Object Meta
	ICAT_COLUMN_META_DATA_ATTR_NAME   ICATColumnNumber = 600
	ICAT_COLUMN_META_DATA_ATTR_VALUE  ICATColumnNumber = 601
	ICAT_COLUMN_META_DATA_ATTR_UNITS  ICATColumnNumber = 602
	ICAT_COLUMN_META_DATA_ATTR_ID     ICATColumnNumber = 603
	ICAT_COLUMN_META_DATA_CREATE_TIME ICATColumnNumber = 604
	ICAT_COLUMN_META_DATA_MODIFY_TIME ICATColumnNumber = 605

	// Collection Meta
	ICAT_COLUMN_META_COLL_ATTR_NAME   ICATColumnNumber = 610
	ICAT_COLUMN_META_COLL_ATTR_VALUE  ICATColumnNumber = 611
	ICAT_COLUMN_META_COLL_ATTR_UNITS  ICATColumnNumber = 612
	ICAT_COLUMN_META_COLL_ATTR_ID     ICATColumnNumber = 613
	ICAT_COLUMN_META_COLL_CREATE_TIME ICATColumnNumber = 614
	ICAT_COLUMN_META_COLL_MODIFY_TIME ICATColumnNumber = 615

	// User Meta
	ICAT_COLUMN_META_USER_ATTR_NAME   ICATColumnNumber = 640
	ICAT_COLUMN_META_USER_ATTR_VALUE  ICATColumnNumber = 641
	ICAT_COLUMN_META_USER_ATTR_UNITS  ICATColumnNumber = 642
	ICAT_COLUMN_META_USER_ATTR_ID     ICATColumnNumber = 643
	ICAT_COLUMN_META_USER_CREATE_TIME ICATColumnNumber = 644
	ICAT_COLUMN_META_USER_MODIFY_TIME ICATColumnNumber = 645

	// Data Object Access
	ICAT_COLUMN_DATA_ACCESS_TYPE     ICATColumnNumber = 700
	ICAT_COLUMN_DATA_ACCESS_NAME     ICATColumnNumber = 701
	ICAT_COLUMN_DATA_TOKEN_NAMESPACE ICATColumnNumber = 702
	ICAT_COLUMN_DATA_ACCESS_USER_ID  ICATColumnNumber = 703
	ICAT_COLUMN_DATA_ACCESS_DATA_ID  ICATColumnNumber = 704

	// Collection Access
	ICAT_COLUMN_COLL_ACCESS_TYPE     ICATColumnNumber = 710
	ICAT_COLUMN_COLL_ACCESS_NAME     ICATColumnNumber = 711
	ICAT_COLUMN_COLL_TOKEN_NAMESPACE ICATColumnNumber = 712
	ICAT_COLUMN_COLL_ACCESS_USER_ID  ICATColumnNumber = 713
	ICAT_COLUMN_COLL_ACCESS_COLL_ID  ICATColumnNumber = 714

	// Group
	ICAT_COLUMN_COLL_USER_GROUP_ID   ICATColumnNumber = 900
	ICAT_COLUMN_COLL_USER_GROUP_NAME ICATColumnNumber = 901

	// Resource
	ICAT_COLUMN_R_RESC_ID             ICATColumnNumber = 301
	ICAT_COLUMN_R_RESC_NAME           ICATColumnNumber = 302
	ICAT_COLUMN_R_ZONE_NAME           ICATColumnNumber = 303
	ICAT_COLUMN_R_TYPE_NAME           ICATColumnNumber = 304
	ICAT_COLUMN_R_CLASS_NAME          ICATColumnNumber = 305
	ICAT_COLUMN_R_LOC                 ICATColumnNumber = 306
	ICAT_COLUMN_R_VAULT_PATH          ICATColumnNumber = 307
	ICAT_COLUMN_R_FREE_SPACE          ICATColumnNumber = 308
	ICAT_COLUMN_R_RESC_INFO           ICATColumnNumber = 309
	ICAT_COLUMN_R_RESC_COMMENT        ICATColumnNumber = 310
	ICAT_COLUMN_R_CREATE_TIME         ICATColumnNumber = 311
	ICAT_COLUMN_R_MODIFY_TIME         ICATColumnNumber = 312
	ICAT_COLUMN_R_RESC_STATUS         ICATColumnNumber = 313
	ICAT_COLUMN_R_FREE_SPACE_TIME     ICATColumnNumber = 314
	ICAT_COLUMN_R_RESC_CHILDREN       ICATColumnNumber = 315
	ICAT_COLUMN_R_RESC_CONTEXT        ICATColumnNumber = 316
	ICAT_COLUMN_R_RESC_PARENT         ICATColumnNumber = 317
	ICAT_COLUMN_R_RESC_PARENT_CONTEXT ICATColumnNumber = 318

	// Quota
	ICAT_COLUMN_QUOTA_USER_ID           ICATColumnNumber = 2000
	ICAT_COLUMN_QUOTA_RESC_ID           ICATColumnNumber = 2001
	ICAT_COLUMN_QUOTA_LIMIT             ICATColumnNumber = 2002
	ICAT_COLUMN_QUOTA_OVER              ICATColumnNumber = 2003
	ICAT_COLUMN_QUOTA_MODIFY_TIME       ICATColumnNumber = 2004
	ICAT_COLUMN_QUOTA_USAGE_USER_ID     ICATColumnNumber = 2010
	ICAT_COLUMN_QUOTA_USAGE_RESC_ID     ICATColumnNumber = 2011
	ICAT_COLUMN_QUOTA_USAGE             ICATColumnNumber = 2012
	ICAT_COLUMN_QUOTA_USAGE_MODIFY_TIME ICATColumnNumber = 2013
	ICAT_COLUMN_QUOTA_RESC_NAME         ICATColumnNumber = 2020
	ICAT_COLUMN_QUOTA_USER_NAME         ICATColumnNumber = 2021
	ICAT_COLUMN_QUOTA_USER_ZONE         ICATColumnNumber = 2022
	ICAT_COLUMN_QUOTA_USER_TYPE         ICATColumnNumber = 2023
)
