package common

// ICATColumnNumber is an ICAT Column number type
type ICATColumnNumber int

// column numbers
const (
	// Collection
	ICAT_COLUMN_COLL_ID          ICATColumnNumber = 500
	ICAT_COLUMN_COLL_NAME        ICATColumnNumber = 501
	ICAT_COLUMN_COLL_PARENT_NAME ICATColumnNumber = 502
	ICAT_COLUMN_COLL_OWNER_NAME  ICATColumnNumber = 503
	ICAT_COLUMN_COLL_OWNER_ZONE  ICATColumnNumber = 504
	ICAT_COLUMN_COLL_MAP_ID      ICATColumnNumber = 505
	ICAT_COLUMN_COLL_INHERITANCE ICATColumnNumber = 506
	ICAT_COLUMN_COLL_COMMENTS    ICATColumnNumber = 507
	ICAT_COLUMN_COLL_CREATE_TIME ICATColumnNumber = 508
	ICAT_COLUMN_COLL_MODIFY_TIME ICATColumnNumber = 509

	// Collection meta
	ICAT_COLUMN_META_COLL_ATTR_NAME   ICATColumnNumber = 610
	ICAT_COLUMN_META_COLL_ATTR_VALUE  ICATColumnNumber = 611
	ICAT_COLUMN_META_COLL_ATTR_UNITS  ICATColumnNumber = 612
	ICAT_COLUMN_META_COLL_ATTR_ID     ICATColumnNumber = 613
	ICAT_COLUMN_META_COLL_CREATE_TIME ICATColumnNumber = 614
	ICAT_COLUMN_META_COLL_MODIFY_TIME ICATColumnNumber = 615
)
